#!/bin/env bash
#This script transfers the file from the client to a server
using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no
"$FILE_PATH" "$USERNAME@$SERVER_IP":~/||{echo"Error:
File transfer failed.";exit 1;}

echo"File transferred successfully to
$username@$server_ip:~/"
